### ISSUE TITLE
Docker Container Report Running issue

### ISSUE THREAD

**Issue by After-Shock** [ninthwalker/NowShowing#51]
Preface - using Cloudbox install.

installed nowshowing via Docker create

```
docker create --name=nowshowing \
-e PLEX_SERVER_IP=172.17.0.11 \
-e PLEX_TOKEN=XXXXXXXXXXXXXXXX \
-e SMTP_SERVER=smtp.gmail.com \
-e SMTP_PORT=587 \
-e PUID=1001 \
-e PGID=1001 \
-e VIRTUAL_HOST=nowshowing.XXXXXX.com \
-e VIRTUAL_PORT=6878 \
-e LETSENCRYPT_HOST=nowshowing.XXXXXXX.com \
-e LETSENCRYPT_EMAIL=admin@XXXXXXX.com \
-e EMAIL_USERNAME=admin@XXXXXX.com \
-e EMAIL_PASSWORD=XXXXXXXX \
-p 6878:6878/tcp \
-v /opt/nowshowing:/config:rw \
-v /etc/localtime:/etc/localtime:ro \
--restart=always \
--net=cloudbox \
ninthwalker/nowshowing`
```
(It's also on the Bridge network but not during creation)

I am able to access the Default webpage just fine, however when attempting to send test email or combined email&webpage I get the following timeout error:

```
docker exec -it nowshowing emailreport -d -t 
[sudo] password for XXXXXX: 
/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
	from /usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
	from /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:1384:in `request'
	from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty/request.rb:93:in `perform'
	from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
	from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty.rb:457:in `get'
	from /var/lib/nowshowing/plex.rb:29:in `get'
	from /usr/local/sbin/emailreport:104:in `getMovies'
	from /usr/local/sbin/emailreport:377:in `main'
	from /usr/local/sbin/emailreport:397:in `<main>'
```
I've also set the normal report to run and obv it timed out as well.  All the log files are empty because no report was run.  Tried a few users on discord and they suggested an Open Ticket here.  Thanks for your time.

**Comment by After-Shock** [comment]
Figured it out.
